### ISSUE TITLE
assistance with setting up docker for heroku using mysql and flask

### ISSUE THREAD

**Issue by trinhsk** [stavshamir/docker-tutorial#1]
Hi, 

I found your article on medium and it helped me a lot. However I still can't get my app running. I have an app that uses mysql db and flask web framework. I understand now that I should use docker compose and followed your instructions. However there is an added element to the difficulty. Heroku requires gunicorn to work in the backend; I'm not too certain on the details but it seems like I need to run the gunicorn command as the entrypoint. I tailored my `docker-compose.yml` file like this: 

```
version: '3.7'
services:
  app:
    build: . 
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - "3306"
    volumes:
      - ./chemITry/app/protected:/docker-entrypoint-initdb.d/:ro 
    entrypoint:
      - startup.sh
```

And my `startup.sh` is:

```
#!/bin/bash
gunicorn --bind 0.0.0.0:5000 run:app 

```

What does the `ro:` at the end of volumes section do? Would you please provide some assistance? I'm very new to all this, just want to get a working app; been battling for a month now. Thanks.
